### ISSUE TITLE
Search Page: Add Styling as per Figma

### ISSUE THREAD

**Issue by jLouzado** [milli-consortium/milli-frontend#3]
# Figma Link

* [Search Page](https://www.figma.com/file/Gc02lSEv5QmWZWqiSLl1tY/Milli-Main?node-id=192%3A0)
  * For the Page, refer the `Desktop - 1` frame
  * for the individual cards, refer `Frame 4` and `Frame 5`

The Frames in Figma are accessible from the Left Panel as shown in the screenshot below:
![image](https://user-images.githubusercontent.com/2016685/119885470-81723800-bf4f-11eb-98f9-7edfa26b3fe4.png)

# Sub-tasks to Complete

- [x] add styling for header, search bar, sidebar, content and footer
- [x] add accordion for sections in sidebar
  * use accordion component from `ant-d` package
- [x]  add styling for individual cards

# Things to Note

Existing implementation is in the `src/pages/search.tsx` :
1. need to use `antd-mobile` components
    * https://www.npmjs.com/package/antd-mobile
1. don't add anything related to pagination
