### ISSUE TITLE
Object Page: Add styling as per Figma

### ISSUE THREAD

**Issue by jLouzado** [milli-consortium/milli-frontend#4]
# Figma Link

* [Object Page](https://www.figma.com/file/Gc02lSEv5QmWZWqiSLl1tY/Milli-Main?node-id=0%3A1)
* Special focus on the following frames:
  * Desktop-3
  * Desktop-4

# Sub-tasks

- [x] add styling to main layout
- [ ] add right-hand side-bar for annotations
- [ ] add top-bar for actions-header (seen on Desktop-4

# Things to Note

* if you add extra fields to a query, you need to re-run `yarn gql:update` to regenerate the typescript typings
* if there are multiple images, let them be rendered one below the other
* reuse the same `Badges` from the Search page when rendering Authors, Subjects, Places, etc
